export const GET_OWN_RESUMES_DATA_REQUEST = "GET_OWN_RESUMES_DATA_REQUEST"
export const GET_OWN_RESUMES_DATA_SUCCESS = "GET_OWN_RESUMES_DATA_SUCCESS"
export const GET_OWN_RESUMES_DATA_ERROR = "GET_OWN_RESUMES_DATA_ERROR"

export const GET_OTHER_RESUME_DATA_REQUEST = "GET_OTHER_RESUME_DATA_REQUEST"
export const GET_OTHER_RESUME_DATA_SUCCESS = "GET_OTHER_RESUME_DATA_SUCCESS"
export const GET_OTHER_RESUME_DATA_ERROR = "GET_OTHER_RESUME_DATA_ERROR"

export const GET_OWN_RESUME_REQUEST = "GET_OWN_RESUME_REQUEST"
export const GET_OWN_RESUME_SUCCESS = "GET_OWN_RESUME_SUCCESS"
export const GET_OWN_RESUME_ERROR = "GET_OWN_RESUME_ERROR"

export const GET_OTHER_RESUME = "GET_OTHER_RESUME"
export const GET_MEDIA_REQUEST = "GET_MEDIA_REQUEST"
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS"
export const GET_MEDIA_ERROR = "GET_MEDIA_ERROR"
export const GET_NATIONALITY = "GET_NATIONALITY"

export const CREATE_RESUME_REQUEST = "CREATE_RESUME_REQUEST"
export const CREATE_RESUME_SUCCESS = "CREATE_RESUME_SUCCESS"
export const CREATE_RESUME_ERROR = "CREATE_RESUME_ERROR"

export const REMOVE_SELECTED_RESUME = "REMOVE_SELECTED_RESUME"
export const CLONE_SELECTED_RESUME = "CLONE_SELECTED_RESUME"
export const SAVE_TO_MY_LIST = "SAVE_TO_MY_LIST"