export const styles = {
    cardsItem: {
        position: "relative",
        display: "flex",
        padding: "0.50rem 0rem",
        marginBottom: "1rem",
        marginRight: "24px",
        height: "164px",
        "@media (max-width: 450px)": {
          margin: "0 auto",
        },
      },
      card: {
        position: "relative",
        width: "132px",
        height: "137px",
        backgroundColor: "#ffffff",
        borderRadius: "0.25rem",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      },
      status: {
        position: "absolute",
        left: "0px",
        top: "6px",
        background: "#29CC8F",
        color: "#fff",
        fontSize: "9px",
        fontWeight: "700",
        padding: "3px 7px",
        textTransform: "uppercase",
        borderRadius: "0px 2px 2px 0px",
      },
      deleteButton: {
        cursor: "pointer",
        position: "absolute",
        right: "15px",
        top: "16px",
        zIndex: "100",
        width: "12px",
        height: "16px",
        color: "#F68C8D",
      },
      detail: {
        width: "100%",
        height: "60%",
        display: "flex",
        alignItems: "end",
        flexDirection: "column",
        justifyContent: "space-between",
      },
      actionBox: {
        display: "flex",
        justifyContent: "space-around",
        width: "100%",
        marginBottom: "10px",
      },
      text: {
        fontSize: "9px",
        marginRight: "6px",
      },
}